禁止ワードチェック

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -17,8 +17,31 @@
 
 # This example catches duplicate Signed-off-by lines.
 
-test "" = "$(grep '^Signed-off-by: ' "$1" |
-	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
-	echo >&2 Duplicate Signed-off-by lines.
-	exit 1
+# test "" = "$(grep '^Signed-off-by: ' "$1" |
+# 	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+# 	echo >&2 Duplicate Signed-off-by lines.
+# 	exit 1
+# }
+
+### Validate prohibited words ###
+# @param $1=commit_editmsg_file
+validateProhibitedRegexWords() {
+    local commit_editmsg_file=$1
+    local prohibited_regex_words=(
+            "[0-9]{4}/[0-9]/[0-9]"
+            "[0-9]{4}/[0-9]{2}/[0-9]"
+            "[0-9]{4}/[0-9]/[0-9]{2}"
+            "f..k"
+            "hoge|fizz|buzz"
+        )
+    for word in "${prohibited_regex_words[@]}"
+    do
+        grep -Ei ${word} ${commit_editmsg_file} > /dev/null
+        if [ $? -eq 0 ]; then
+            echo "*** Can't commit! ***"
+            echo "[CAUSE] Commit-message include the prohibited regex word : '$word'. Fix your Commit-meesage."
+            exit 1
+        fi
+    done
 }
+validateProhibitedRegexWords $1
